services:
  - type: web
    name: nias
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PORT
        value: 8080
      - key: PYTHON_VERSION
        value: 3.11.9
